#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────────────
# self-deploy.sh  —  AWS self-deployment, made easy
#
# Usage:  ./scripts/self-deploy.sh <ENV>
#   ENV   environment name — must have a matching env/<ENV>.tfvars
#         (e.g. dev, qa, staging, test, client1)
#
# What it does, in plain terms:
#   1. Creates the scoped IAM user Terraform needs (not admin/root access)
#   2. Generates strong passwords for you (or accepts your own)
#   3. Creates the AWS Secrets Manager secrets Terraform reads at deploy time
#   4. Updates env/<ENV>.tfvars with the new ArgoCD password hash
#   5. Saves everything it generated to a local file (chmod 600) so nothing
#      is lost — you copy that into your password manager, then delete it
#   6. Optionally runs the actual Terraform deploy — 2 applies (repo root,
#      then cicd/; down from 4 separate layers in the original design, but
#      not all the way to 1 — see cicd/main.tf's file header for why),
#      after one clear confirmation, since that step creates real cloud
#      resources and costs money
#
# You do NOT need to know Terraform, IAM policies, or bcrypt to run this.
# Everything it creates is idempotent — safe to re-run if it fails partway.
#
# Requires: aws cli, htpasswd, openssl, jq, dig, terraform. The identity aws cli
#           is configured with only needs permission to manage one IAM user
#           and two IAM policies -- see ../PERMISSIONS.md for the exact
#           policy, not full account admin.
# ──────────────────────────────────────────────────────────────────────────────
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

if [[ $# -lt 1 ]]; then
  echo "Usage: $0 <ENV>"
  echo "  ENV  must have a matching env/<ENV>.tfvars (e.g. dev, qa, staging, test, client1)"
  exit 1
fi
ENV="$1"
TFVARS="${REPO_ROOT}/env/${ENV}.tfvars"

if [[ ! -f "${TFVARS}" ]]; then
  echo "ERROR: ${TFVARS} not found."
  echo "Create env/${ENV}.tfvars first (with a 'pipelines' block for the services you want)."
  exit 1
fi

for bin in aws htpasswd openssl jq dig terraform; do
  command -v "$bin" >/dev/null 2>&1 || { echo "ERROR: '$bin' is required but not installed."; exit 1; }
done

echo "════════════════════════════════════════════════════════════════"
echo " Ekai AWS self-deploy — environment: ${ENV}"
echo "════════════════════════════════════════════════════════════════"
echo

REGION=$(grep -E '^region\s*=' "${TFVARS}" | head -1 | sed 's/.*=\s*"\(.*\)".*/\1/')
[[ -z "${REGION}" ]] && { echo "ERROR: could not read 'region' from ${TFVARS}"; exit 1; }
echo "==> Region: ${REGION}"

CICD_PROVIDER=$(grep -E '^cicd_provider\s*=' "${TFVARS}" | head -1 | sed 's/.*=\s*"\(.*\)".*/\1/')
if [[ "${CICD_PROVIDER}" == "none" ]]; then
  echo "==> cicd_provider = \"none\" (self-service) — the cluster/platform"
  echo "    submodules generate RDS/ArgoCD credentials directly, no master secret needed."
fi

ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
echo "==> AWS account: ${ACCOUNT_ID}"
echo "==> Currently authenticated as: $(aws sts get-caller-identity --query Arn --output text)"
if [[ "${CICD_PROVIDER}" == "none" ]]; then
  echo "    (this identity only needs permission to manage one IAM user + two"
  echo "     IAM policies — see PERMISSIONS.md for the exact policy. It is NOT"
  echo "     the identity Terraform will use.)"
else
  echo "    (this identity needs IAM permissions per PERMISSIONS.md, plus Secrets"
  echo "     Manager create/read/write for the master + per-service secrets"
  echo "     Step 3 below creates. It is NOT the identity Terraform will use.)"
fi
echo

OUT_DIR="${REPO_ROOT}/.self-deploy"
mkdir -p "${OUT_DIR}"
SECRETS_FILE="${OUT_DIR}/${ENV}-generated-secrets.txt"
: > "${SECRETS_FILE}"
chmod 600 "${SECRETS_FILE}"
echo "# Generated by self-deploy.sh for env=${ENV} — copy into your password manager, then delete this file" >> "${SECRETS_FILE}"

# ── Step 1 — IAM user + scoped policies ───────────────────────────────────────
echo "──── Step 1/4: IAM user ────────────────────────────────────────────"
USER_NAME="ekai-terraform-${ENV}"
INFRA_POLICY_NAME="ekai-terraform-policy-infra"
CICD_POLICY_NAME="ekai-terraform-policy-cicd"
INFRA_ARN="arn:aws:iam::${ACCOUNT_ID}:policy/${INFRA_POLICY_NAME}"
CICD_ARN="arn:aws:iam::${ACCOUNT_ID}:policy/${CICD_POLICY_NAME}"

POLICY_DIR=$(mktemp -d)
trap 'rm -rf "${POLICY_DIR}"' EXIT

cat > "${POLICY_DIR}/infra.json" <<'POLICY'
{
  "Version": "2012-10-17",
  "Statement": [
    { "Sid": "VPCNetworking", "Effect": "Allow", "Action": [
        "ec2:AllocateAddress","ec2:AssociateRouteTable","ec2:AttachInternetGateway",
        "ec2:AuthorizeSecurityGroupEgress","ec2:AuthorizeSecurityGroupIngress",
        "ec2:CreateInternetGateway","ec2:CreateNatGateway","ec2:CreateRoute",
        "ec2:CreateRouteTable","ec2:CreateSecurityGroup","ec2:CreateSubnet",
        "ec2:CreateTags","ec2:DeleteTags","ec2:CreateVpc","ec2:DeleteInternetGateway",
        "ec2:DeleteNatGateway","ec2:DeleteRoute","ec2:DeleteRouteTable",
        "ec2:DeleteSecurityGroup","ec2:DeleteSubnet","ec2:DeleteVpc",
        "ec2:DescribeAddresses","ec2:DescribeAvailabilityZones",
        "ec2:DescribeInternetGateways","ec2:DescribeNatGateways",
        "ec2:DescribeNetworkInterfaces","ec2:DescribeRouteTables",
        "ec2:DescribeSecurityGroups","ec2:DescribeSubnets","ec2:DescribeTags",
        "ec2:DescribeVpcAttribute","ec2:DescribeVpcs",
        "ec2:DetachInternetGateway","ec2:DisassociateAddress",
        "ec2:DisassociateRouteTable","ec2:ModifySubnetAttribute",
        "ec2:ModifyVpcAttribute","ec2:ReleaseAddress",
        "ec2:RevokeSecurityGroupEgress","ec2:RevokeSecurityGroupIngress",
        "ec2:CreateNetworkInterface","ec2:DeleteNetworkInterface",
        "ec2:DescribeInstanceTypes","ec2:DescribeDhcpOptions",
        "ec2:DescribeAddressesAttribute",
        "ec2:DescribeVpcEndpoints","ec2:DeleteVpcEndpoints",
        "ec2:DescribeVpcEndpointServices"
      ], "Resource": "*" },
    { "Sid": "LoadBalancerCleanup", "Effect": "Allow", "Action": [
        "elasticloadbalancing:DescribeLoadBalancers","elasticloadbalancing:DescribeLoadBalancerAttributes",
        "elasticloadbalancing:DescribeTargetGroups","elasticloadbalancing:DescribeTargetGroupAttributes",
        "elasticloadbalancing:DescribeListeners","elasticloadbalancing:DescribeListenerAttributes",
        "elasticloadbalancing:DescribeRules","elasticloadbalancing:DescribeTags",
        "elasticloadbalancing:DeleteLoadBalancer","elasticloadbalancing:DeleteTargetGroup",
        "elasticloadbalancing:DeleteListener"
      ], "Resource": "*" },
    { "Sid": "Kubernetes", "Effect": "Allow", "Action": [
        "eks:CreateCluster","eks:DeleteCluster","eks:DescribeCluster",
        "eks:UpdateClusterConfig","eks:UpdateClusterVersion",
        "eks:CreateNodegroup","eks:DeleteNodegroup","eks:DescribeNodegroup",
        "eks:UpdateNodegroupConfig","eks:CreateAddon","eks:DeleteAddon",
        "eks:DescribeAddon","eks:UpdateAddon","eks:ListAddons","eks:DescribeUpdate",
        "eks:ListClusters","eks:ListNodegroups","eks:TagResource","eks:UntagResource"
      ], "Resource": "*" },
    { "Sid": "AutoscalerASGTags", "Effect": "Allow", "Action": [
        "autoscaling:CreateOrUpdateTags","autoscaling:DeleteTags",
        "autoscaling:DescribeAutoScalingGroups","autoscaling:DescribeTags"
      ], "Resource": "*" },
    { "Sid": "Database", "Effect": "Allow", "Action": [
        "rds:CreateDBInstance","rds:DeleteDBInstance","rds:DescribeDBInstances",
        "rds:ModifyDBInstance","rds:RebootDBInstance",
        "rds:CreateDBSubnetGroup","rds:DeleteDBSubnetGroup",
        "rds:DescribeDBSubnetGroups","rds:ModifyDBSubnetGroup",
        "rds:CreateDBParameterGroup","rds:DeleteDBParameterGroup",
        "rds:DescribeDBParameterGroups","rds:ModifyDBParameterGroup",
        "rds:AddTagsToResource","rds:ListTagsForResource",
        "rds:DescribeDBEngineVersions","rds:DescribeOrderableDBInstanceOptions"
      ], "Resource": "*" },
    { "Sid": "IAMForCluster", "Effect": "Allow", "Action": [
        "iam:CreateRole","iam:DeleteRole","iam:GetRole","iam:UpdateRole","iam:ListRoles",
        "iam:CreatePolicy","iam:DeletePolicy","iam:GetPolicy",
        "iam:GetPolicyVersion","iam:ListPolicies","iam:ListPolicyVersions",
        "iam:CreatePolicyVersion","iam:DeletePolicyVersion",
        "iam:AttachRolePolicy","iam:DetachRolePolicy","iam:ListAttachedRolePolicies",
        "iam:PutRolePolicy","iam:DeleteRolePolicy","iam:GetRolePolicy","iam:ListRolePolicies",
        "iam:PutUserPolicy","iam:DeleteUserPolicy","iam:GetUserPolicy","iam:ListUserPolicies",
        "iam:CreateInstanceProfile","iam:DeleteInstanceProfile",
        "iam:GetInstanceProfile","iam:ListInstanceProfilesForRole",
        "iam:AddRoleToInstanceProfile","iam:RemoveRoleFromInstanceProfile",
        "iam:TagRole","iam:UntagRole","iam:TagPolicy","iam:UntagPolicy",
        "iam:CreateOpenIDConnectProvider","iam:DeleteOpenIDConnectProvider",
        "iam:GetOpenIDConnectProvider","iam:ListOpenIDConnectProviders",
        "iam:TagOpenIDConnectProvider"
      ], "Resource": "*" },
    { "Sid": "IAMPassRole", "Effect": "Allow", "Action": "iam:PassRole",
      "Resource": "arn:aws:iam::ACCOUNT_ID:role/*",
      "Condition": { "StringEquals": { "iam:PassedToService": [
        "eks.amazonaws.com","ec2.amazonaws.com","codebuild.amazonaws.com","amplify.amazonaws.com"
      ] } } },
    { "Sid": "IAMServiceLinkedRole", "Effect": "Allow", "Action": "iam:CreateServiceLinkedRole",
      "Resource": "arn:aws:iam::ACCOUNT_ID:role/aws-service-role/*",
      "Condition": { "StringEquals": { "iam:AWSServiceName": [
        "eks.amazonaws.com","elasticloadbalancing.amazonaws.com","ec2.amazonaws.com","rds.amazonaws.com"
      ] } } }
  ]
}
POLICY

# ApplicationSecrets below assumes every secret name this script or Terraform
# creates contains the substring "ekai" somewhere (true for both the old
# per-service "<env>-ekai-<service>" convention and the self-service default
# "ekai-customer") — if a client renames customer_secret_name to something
# with no "ekai" in it, widen that pattern to match.
#
# ApplicationFileStorage wildcards s3:* -- aws_s3_bucket's refresh reads a
# long tail of per-bucket sub-resource APIs (ACL, CORS, logging, lifecycle,
# website, replication, object lock, tagging, ...), each its own AccessDenied
# if missing, so granular actions turn into permanent whack-a-mole. Safe to
# wildcard only because Resource is the EXACT bucket name the cicd submodule's
# Terraform hardcodes (ekai-<env>-<account_id>) -- NOT a "ekai-*" glob, which would also
# match "ekai-terraform-state-*" and hand this identity full S3 control over
# the Terraform state bucket.
cat > "${POLICY_DIR}/cicd.json" <<'POLICY'
{
  "Version": "2012-10-17",
  "Statement": [
    { "Sid": "CICD", "Effect": "Allow", "Action": [
        "codebuild:CreateProject","codebuild:DeleteProject",
        "codebuild:UpdateProject","codebuild:BatchGetProjects",
        "codebuild:CreateWebhook","codebuild:DeleteWebhook","codebuild:UpdateWebhook",
        "codebuild:ImportSourceCredentials","codebuild:DeleteSourceCredentials",
        "codebuild:ListSourceCredentials",
        "ecr:GetAuthorizationToken","ecr:BatchCheckLayerAvailability",
        "ecr:GetDownloadUrlForLayer","ecr:BatchGetImage",
        "ecr:PutImage","ecr:InitiateLayerUpload","ecr:UploadLayerPart",
        "ecr:CompleteLayerUpload","ecr:CreateRepository","ecr:DeleteRepository",
        "ecr:DescribeRepositories","ecr:ListImages","ecr:TagResource",
        "ecr:ListTagsForResource","ecr:UntagResource",
        "ecr:GetLifecyclePolicy","ecr:PutLifecyclePolicy","ecr:DeleteLifecyclePolicy",
        "ecr:PutImageTagMutability","ecr:GetRepositoryPolicy",
        "ecr:SetRepositoryPolicy","ecr:DeleteRepositoryPolicy"
      ], "Resource": "*" },
    { "Sid": "FrontendHosting", "Effect": "Allow", "Action": [ "amplify:*" ], "Resource": "*" },
    { "Sid": "DNSandCerts", "Effect": "Allow", "Action": [
        "route53:*",
        "acm:RequestCertificate","acm:DescribeCertificate","acm:DeleteCertificate",
        "acm:GetCertificate","acm:ListCertificates","acm:ListTagsForCertificate",
        "acm:AddTagsToCertificate"
      ], "Resource": "*" },
    { "Sid": "Observability", "Effect": "Allow", "Action": [
        "logs:CreateLogGroup","logs:DeleteLogGroup",
        "logs:CreateLogStream","logs:DeleteLogStream",
        "logs:DescribeLogGroups","logs:DescribeLogStreams",
        "logs:PutRetentionPolicy","logs:DeleteRetentionPolicy"
      ], "Resource": "*" },
    { "Sid": "TerraformState", "Effect": "Allow", "Action": [
        "s3:CreateBucket","s3:DeleteBucket","s3:ListBucket",
        "s3:GetBucketLocation","s3:GetBucketVersioning","s3:PutBucketVersioning",
        "s3:GetEncryptionConfiguration","s3:PutEncryptionConfiguration",
        "s3:GetBucketPublicAccessBlock","s3:PutBucketPublicAccessBlock",
        "s3:GetObject","s3:PutObject","s3:DeleteObject",
        "s3:GetObjectVersion","s3:DeleteObjectVersion","s3:ListBucketVersions"
      ], "Resource": [ "arn:aws:s3:::ekai-terraform-state-*", "arn:aws:s3:::ekai-terraform-state-*/*" ] },
    { "Sid": "ApplicationFileStorage", "Effect": "Allow", "Action": [ "s3:*" ],
      "Resource": [ "arn:aws:s3:::ekai-ENV_NAME-ACCOUNT_ID", "arn:aws:s3:::ekai-ENV_NAME-ACCOUNT_ID/*" ] },
    { "Sid": "ApplicationSecrets", "Effect": "Allow", "Action": [
        "secretsmanager:CreateSecret","secretsmanager:DeleteSecret",
        "secretsmanager:DescribeSecret","secretsmanager:GetSecretValue",
        "secretsmanager:ListSecrets","secretsmanager:PutSecretValue",
        "secretsmanager:UpdateSecret","secretsmanager:TagResource","secretsmanager:UntagResource",
        "secretsmanager:GetResourcePolicy","secretsmanager:PutResourcePolicy","secretsmanager:DeleteResourcePolicy"
      ], "Resource": [ "arn:aws:secretsmanager:*:*:secret:*ekai*" ] },
    { "Sid": "KMS", "Effect": "Allow", "Action": [
        "kms:CreateKey","kms:CreateAlias","kms:DescribeKey",
        "kms:EnableKeyRotation","kms:GenerateDataKey","kms:Decrypt",
        "kms:ListAliases","kms:TagResource"
      ], "Resource": "*" }
  ]
}
POLICY

sed -i "s/ACCOUNT_ID/${ACCOUNT_ID}/g" "${POLICY_DIR}/infra.json"
sed -i "s/ACCOUNT_ID/${ACCOUNT_ID}/g; s/ENV_NAME/${ENV}/g" "${POLICY_DIR}/cicd.json"

# "Already exists" alone isn't enough to skip -- this script's own embedded
# policy documents change over time (e.g. a missing action discovered later),
# and an existing customer's live policy needs those fixes to actually reach
# their account. Compare documents and publish a new version when they drift.
for pair in "${INFRA_POLICY_NAME}:${POLICY_DIR}/infra.json" "${CICD_POLICY_NAME}:${POLICY_DIR}/cicd.json"; do
  PNAME="${pair%%:*}"; PFILE="${pair#*:}"
  PARN="arn:aws:iam::${ACCOUNT_ID}:policy/${PNAME}"
  if aws iam get-policy --policy-arn "${PARN}" >/dev/null 2>&1; then
    CURRENT_VERSION=$(aws iam get-policy --policy-arn "${PARN}" --query 'Policy.DefaultVersionId' --output text)
    CURRENT_DOC=$(aws iam get-policy-version --policy-arn "${PARN}" --version-id "${CURRENT_VERSION}" --query 'PolicyVersion.Document' --output json | jq -S .)
    NEW_DOC=$(jq -S . "${PFILE}")
    if [[ "${CURRENT_DOC}" == "${NEW_DOC}" ]]; then
      echo "==> Policy ${PNAME} already up to date (${CURRENT_VERSION}) — reusing."
    else
      echo "==> Policy ${PNAME} exists but its permissions have changed — publishing a new version."
      VERSION_COUNT=$(aws iam list-policy-versions --policy-arn "${PARN}" --query 'length(Versions)' --output text)
      if [[ "${VERSION_COUNT}" -ge 5 ]]; then
        OLDEST_NON_DEFAULT=$(aws iam list-policy-versions --policy-arn "${PARN}" --query 'Versions[?IsDefaultVersion==`false`]|sort_by(@, &CreateDate)[0].VersionId' --output text)
        echo "    (at IAM's 5-version limit — deleting oldest non-default version ${OLDEST_NON_DEFAULT})"
        aws iam delete-policy-version --policy-arn "${PARN}" --version-id "${OLDEST_NON_DEFAULT}"
      fi
      aws iam create-policy-version --policy-arn "${PARN}" --policy-document "file://${PFILE}" --set-as-default >/dev/null
      echo "✓ ${PNAME} updated."
    fi
  else
    echo "==> Creating policy ${PNAME}..."
    aws iam create-policy --policy-name "${PNAME}" --policy-document "file://${PFILE}" >/dev/null
  fi
done

if aws iam get-user --user-name "${USER_NAME}" >/dev/null 2>&1; then
  echo "==> IAM user ${USER_NAME} already exists — reusing."
else
  echo "==> Creating IAM user ${USER_NAME}..."
  aws iam create-user --user-name "${USER_NAME}" >/dev/null
fi

aws iam attach-user-policy --user-name "${USER_NAME}" --policy-arn "${INFRA_ARN}"
aws iam attach-user-policy --user-name "${USER_NAME}" --policy-arn "${CICD_ARN}"
echo "==> Policies attached to ${USER_NAME}."

# AWS never returns an existing key's secret again, and this script truncates
# SECRETS_FILE on every run — so a previously created key's secret is always
# unrecoverable by the time this runs a second time. Reusing "whatever's
# ambient" instead of this exact user is not a safe fallback: EKS clusters
# created with authentication_mode = CONFIG_MAP (this codebase's default,
# see the cluster submodule's kubernetes_config_map_v1_data.aws_auth) grant
# automatic access ONLY to the IAM identity that created the cluster. Any
# other identity — including the operator's own default AWS credentials —
# gets "Unauthorized" on every Kubernetes/Helm resource in this same apply.
# So: always mint a fresh key for USER_NAME and deactivate old ones, rather
# than ever falling back to ambient credentials.
mapfile -t EXISTING_KEYS < <(aws iam list-access-keys --user-name "${USER_NAME}" --query 'sort_by(AccessKeyMetadata, &CreateDate)[].AccessKeyId' --output text | tr '\t' '\n')
if [[ ${#EXISTING_KEYS[@]} -ge 2 ]]; then
  echo "==> ${USER_NAME} already has 2 access keys (AWS's max) — deleting the oldest (${EXISTING_KEYS[0]}) to make room."
  aws iam delete-access-key --user-name "${USER_NAME}" --access-key-id "${EXISTING_KEYS[0]}"
  EXISTING_KEYS=("${EXISTING_KEYS[@]:1}")
fi

echo "==> Creating a fresh access key for ${USER_NAME}..."
AK_JSON=$(aws iam create-access-key --user-name "${USER_NAME}")
TF_AWS_ACCESS_KEY_ID=$(echo "${AK_JSON}" | jq -r .AccessKey.AccessKeyId)
TF_AWS_SECRET_ACCESS_KEY=$(echo "${AK_JSON}" | jq -r .AccessKey.SecretAccessKey)
{
  echo "AWS_ACCESS_KEY_ID=${TF_AWS_ACCESS_KEY_ID}"
  echo "AWS_SECRET_ACCESS_KEY=${TF_AWS_SECRET_ACCESS_KEY}"
} >> "${SECRETS_FILE}"
echo "==> Access key created: ${TF_AWS_ACCESS_KEY_ID} (secret saved to ${SECRETS_FILE})"

for OLD_KEY in "${EXISTING_KEYS[@]}"; do
  echo "==> Deactivating previous access key ${OLD_KEY} (its secret is no longer known to this script)."
  aws iam update-access-key --user-name "${USER_NAME}" --access-key-id "${OLD_KEY}" --status Inactive
done
echo

# ── Step 2 — Passwords ────────────────────────────────────────────────────────
echo "──── Step 2/4: Passwords ───────────────────────────────────────────"
if [[ "${CICD_PROVIDER}" == "none" ]]; then
  echo "==> cicd_provider = \"none\" (self-service) — the platform submodule generates"
  echo "    its own ArgoCD admin password, the cluster submodule its own RDS"
  echo "    credentials. Skipping."
  echo "    Retrieve the ArgoCD password after apply: it's also in the customer"
  echo "    secret's ARGOCD_PASSWORD key, or run (from examples/self-deploy/root)"
  echo "    terraform output -raw argocd_admin_password"
else
  echo "Leave any prompt blank to auto-generate a strong random value."
  read -rsp "ArgoCD admin password (blank = auto-generate): " ARGOCD_PW; echo
  [[ -z "${ARGOCD_PW}" ]] && ARGOCD_PW=$(openssl rand -base64 24 | tr -dc 'A-Za-z0-9' | head -c 24)
  ARGOCD_HASH=$(htpasswd -nbBC 12 "" "${ARGOCD_PW}" | tr -d ':\n' | sed 's/$2y/$2a/')

  read -rsp "Backend DB password (blank = auto-generate): " BACKEND_DB_PW; echo
  [[ -z "${BACKEND_DB_PW}" ]] && BACKEND_DB_PW=$(openssl rand -base64 24 | tr -dc 'A-Za-z0-9' | head -c 24)

  read -rsp "Semantics DB password (blank = auto-generate): " SEMANTICS_DB_PW; echo
  [[ -z "${SEMANTICS_DB_PW}" ]] && SEMANTICS_DB_PW=$(openssl rand -base64 24 | tr -dc 'A-Za-z0-9' | head -c 24)

  {
    echo "argocd_admin_password_plain=${ARGOCD_PW}"
    echo "backend_db_password=${BACKEND_DB_PW}"
    echo "semantics_db_password=${SEMANTICS_DB_PW}"
  } >> "${SECRETS_FILE}"

  echo "==> Updating argocd_admin_password_hashed in ${TFVARS}..."
  sed -i "s|^argocd_admin_password_hashed.*|argocd_admin_password_hashed = \"${ARGOCD_HASH}\"|" "${TFVARS}"
fi
echo

# ── Step 3 — Secrets Manager ──────────────────────────────────────────────────
echo "──── Step 3/4: Secrets Manager ─────────────────────────────────────"
if [[ "${CICD_PROVIDER}" == "none" ]]; then
  echo "==> cicd_provider = \"none\" (self-service) — no master secret, no"
  echo "    per-service secrets. The cluster/platform/cicd submodules generate and"
  echo "    create everything they need directly. Skipping this step entirely."
else
  MASTER_SECRET="${ENV}-ekai-db-credentials"

  if aws secretsmanager describe-secret --secret-id "${MASTER_SECRET}" --region "${REGION}" >/dev/null 2>&1; then
    echo "==> ${MASTER_SECRET} already exists — not overwriting (it may already be in use)."
    echo "    Update it manually if needed: aws secretsmanager put-secret-value --secret-id ${MASTER_SECRET} ..."
  else
    echo "==> Creating ${MASTER_SECRET}..."
    aws secretsmanager create-secret \
      --name "${MASTER_SECRET}" \
      --region "${REGION}" \
      --secret-string "$(jq -n \
        --arg bu "ekai_backend" --arg bp "${BACKEND_DB_PW}" --arg bn "ekai_backend" \
        --arg su "ekai_semantics" --arg sp "${SEMANTICS_DB_PW}" --arg sn "ekai_semantics" \
        --arg ap "${ARGOCD_PW}" \
        '{backend_db_username:$bu, backend_db_password:$bp, backend_db_name:$bn,
          semantics_db_username:$su, semantics_db_password:$sp, semantics_db_name:$sn,
          argocd_admin_password: $ap,
          github_token:"EKAI-PROVIDES-THIS", github_username:"EKAI-PROVIDES-THIS", github_email:"EKAI-PROVIDES-THIS"}')" \
      >/dev/null
    echo "✓ ${MASTER_SECRET} created. github_token/username/email are placeholders —"
    echo "  fill in the real GitHub PAT before running terraform apply (needs repo, admin:repo_hook, workflow scopes)."
  fi

  for SVC in ekai-backend ekai-erd ekai-semantics ekai-profile; do
    SNAME="${ENV}-${SVC}"
    if aws secretsmanager describe-secret --secret-id "${SNAME}" --region "${REGION}" >/dev/null 2>&1; then
      echo "==> ${SNAME} already exists — skipping."
    else
      aws secretsmanager create-secret --name "${SNAME}" --region "${REGION}" --secret-string "{}" >/dev/null
      echo "✓ ${SNAME} created (empty — Ekai populates DATABASE_URL etc. after infra deploy)."
    fi
  done
fi
echo

# ── Step 4 — Deploy (optional) ────────────────────────────────────────────────
echo "──── Step 4/4: Deploy infrastructure ───────────────────────────────"
echo "Everything above is prep — no cloud infrastructure has been created yet."
echo "This next step creates real AWS resources (VPC, EKS, RDS, ...) and costs money."
echo
read -rp "Run the Terraform deploy now (2 applies — bootstrap+cluster+platform, then cicd)? [y/N] " CONFIRM
if [[ ! "${CONFIRM}" =~ ^[Yy]$ ]]; then
  echo
  echo "Skipped. When you're ready, deploy locally:"
  echo "  ${SCRIPT_DIR}/init-state-backend.sh ${ENV}"
  echo "  cd ${REPO_ROOT}/examples/self-deploy/root"
  echo "  terraform init -backend-config=../../../env/backend-${ENV}.tfbackend"
  echo "  terraform apply -var-file=../../../env/${ENV}.tfvars"
  echo "  cd ../cicd"
  echo "  terraform init -backend-config=../../../env/backend-${ENV}-cicd.tfbackend"
  echo "  terraform apply -var-file=../../../env/${ENV}.tfvars"
  echo "(use the AWS_ACCESS_KEY_ID/AWS_SECRET_ACCESS_KEY values in ${SECRETS_FILE} if a new key was created above)"
  echo
  echo "Generated secrets are saved at: ${SECRETS_FILE}"
  echo "Copy them into your password manager, then delete the file."
  exit 0
fi

echo "==> Waiting for the new IAM key to propagate..."
for i in $(seq 1 10); do
  if AWS_ACCESS_KEY_ID="${TF_AWS_ACCESS_KEY_ID}" AWS_SECRET_ACCESS_KEY="${TF_AWS_SECRET_ACCESS_KEY}" \
     aws sts get-caller-identity >/dev/null 2>&1; then
    echo "✓ Key is active."
    break
  fi
  sleep 3
done
export AWS_ACCESS_KEY_ID="${TF_AWS_ACCESS_KEY_ID}"
export AWS_SECRET_ACCESS_KEY="${TF_AWS_SECRET_ACCESS_KEY}"

echo "==> Initializing state backend..."
"${SCRIPT_DIR}/init-state-backend.sh" "${ENV}"

# 2 applies, in order: bootstrap+cluster+platform first (its state feeds
# cicd's terraform_remote_state read — see cicd/main.tf's file header for why
# cicd can't be folded into this same apply), then cicd. Both run from
# examples/self-deploy/{root,cicd} — the repo root and cicd/ directories are
# pure Terraform modules now (no backend block of their own; see
# providers.tf / cicd/providers.tf), so they can't be applied directly.
# examples/self-deploy/{root,cicd} are the actual state-holding root configs
# that wrap them — see examples/self-deploy/root/main.tf's header comment.
echo
echo "════════ terraform apply (bootstrap + cluster + platform) ════════"
cd "${REPO_ROOT}/examples/self-deploy/root"
terraform init -upgrade -reconfigure -backend-config="../../../env/backend-${ENV}.tfbackend"
terraform apply -auto-approve -compact-warnings -var-file="../../../env/${ENV}.tfvars"

# ── DNS delegation — only when Terraform just created a NEW Route53 zone.
# Delegating dns_zone to AWS's nameservers at your registrar/parent zone is
# out-of-band and human-timed -- Terraform has no access to do it for you.
# Until it's done, ACM certificate validation (DNS-01 style CNAME) can't
# succeed, and every later Terraform action that waits on that cert
# (aws_acm_certificate_validation) hangs for a very long time before ever
# reporting failure. Same class of issue GCP's self-deploy.sh checks for
# (cert-manager's ACME challenge) -- see that script's comments.
MANAGE_DNS_ZONE=$(grep -E '^manage_dns_zone\s*=' "${TFVARS}" | head -1 | sed 's/.*=\s*\(true\|false\).*/\1/')
if [[ "${MANAGE_DNS_ZONE}" == "true" ]]; then
  DNS_ZONE=$(grep -E '^dns_zone\s*=' "${TFVARS}" | head -1 | sed 's/.*=\s*"\(.*\)".*/\1/')
  # Strip trailing dots on both sides before comparing -- Route53's own API
  # (and this output) return bare hostnames with no trailing dot, but dig
  # always returns FQDNs with one; normalizing both avoids a false
  # "not propagated" mismatch either way. Verified against real Route53
  # zones and real dig output before shipping this (not just a syntax check).
  ZONE_NS=$(terraform output -json route53_name_servers 2>/dev/null | jq -r '.[]' | sed 's/\.$//' | sort)
  if [[ -n "${ZONE_NS}" ]]; then
    echo
    echo "════════ DNS delegation required ════════"
    echo "Terraform just created a Route53 zone for ${DNS_ZONE}. Add an NS"
    echo "record for ${DNS_ZONE} at your domain registrar (or your parent DNS"
    echo "zone) pointing at each of these nameservers:"
    echo "${ZONE_NS}" | sed 's/^/  /'
    echo
    read -rp "Press Enter once you've added it (Ctrl-C to do this later and re-run) " _
    echo "==> Checking DNS delegation (this can take several minutes to propagate)..."
    for i in $(seq 1 40); do
      RESOLVED=$(dig +short NS "${DNS_ZONE}" @8.8.8.8 2>/dev/null | sed 's/\.$//' | sort)
      if [[ -n "${RESOLVED}" && "${RESOLVED}" == "${ZONE_NS}" ]]; then
        echo "✓ DNS delegation confirmed."
        break
      fi
      echo "  Not propagated yet (attempt ${i}/40) — waiting 15s..."
      sleep 15
    done
    if [[ "${RESOLVED}" != "${ZONE_NS}" ]]; then
      echo "⚠ Still not resolving after 10 minutes — ACM certificate validation"
      echo "  will keep failing until this delegation is correct. No need to"
      echo "  re-run this script for that; the validation resource keeps"
      echo "  waiting on its own once delegation is fixed."
    fi
  fi
fi

echo
echo "════════ terraform apply (cicd) ════════"
cd "${REPO_ROOT}/examples/self-deploy/cicd"
terraform init -upgrade -reconfigure -backend-config="../../../env/backend-${ENV}-cicd.tfbackend"
terraform apply -auto-approve -compact-warnings -var-file="../../../env/${ENV}.tfvars"

echo
echo "✓ Deploy complete for env=${ENV}."
echo "Generated secrets are saved at: ${SECRETS_FILE} — copy into your password manager, then delete the file."
